Repository FLira2000/String, pull requests merged in 2019-11, with the labels that each got.

#3 creating the lib itself
  String.c
  String.h
  main.c
Labels: documentation

#4 Update README.md
  README.md
  String.c
  String.h
Labels: documentation

#8 Method 'setString' created #7
  String.c
  String.h
  main.c
Labels: enhancement

#10 Bug fix setString Method
  String.c
  String.h
  main.c
Labels: bug
